sudo: false
dist: xenial

services:
  - mysql

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.1
      env:
        - WP_VERSION=latest
        - IS_TRAVIS=1
        - PHP_VERSION = 7.1
    - php: 7.2
      env:
        - WP_VERSION=latest
        - IS_TRAVIS=1
        - PHP_VERSION = 7.2
    - php: 7.2
      env:
      - SNIFF = 1
      - IS_TRAVIS=1

before_install:
  - if [[ "$SNIFF" == "1" ]]; then export PHPCS_DIR=/tmp/phpcs; fi
  - if [[ "$SNIFF" == "1" ]]; then export SNIFFS_DIR=/tmp/sniffs; fi
  - if [[ "$SNIFF" == "1" ]]; then git clone -b master --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git $PHPCS_DIR; fi
  - if [[ "$SNIFF" == "1" ]]; then git clone -b master --depth 1 https://github.com/WordPress/WordPress-Coding-Standards.git $SNIFFS_DIR; fi
  - if [[ "$SNIFF" == "1" ]]; then $PHPCS_DIR/bin/phpcs --config-set installed_paths $SNIFFS_DIR; fi
  - if [[ "$SNIFF" == "1" ]]; then phpenv rehash; fi

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      if [[ "$PHP_VERSION == 7.2" ]] ; then
        composer install
      else
        composer global require "phpunit/phpunit=7.0"
        composer global require "10up/wp_mock=0.4.2"
      fi
    fi

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      phpunit
      WP_MULTISITE=1 phpunit
    fi
  - |
    if [[ "$SNIFF" == "1" ]]; then
      $PHPCS_DIR/bin/phpcs -p . --standard=WordPress;
    fi
